services:
  opensis:
    build: .
    ports:
      - "8080:80"
    volumes:
      - opensis_data:/var/www/html
    depends_on:
      db:
        condition: service_healthy
    networks:
      - opensis_network

  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      retries: 5
      start_period: 20s
    networks:
      - opensis_network

volumes:
  db_data:
  opensis_data:

networks:
  opensis_network:
