apiVersion: v1
kind: Secret
metadata:
  name: opensis-db-secret
type: Opaque
data:
  MYSQL_ROOT_PASSWORD: {{ .Values.db.rootPassword | b64enc }}
  MYSQL_DATABASE: {{ .Values.db.database | b64enc }}
  MYSQL_USER: {{ .Values.db.user | b64enc }}
  MYSQL_PASSWORD: {{ .Values.db.password | b64enc }}
